mittprojekt/mittprojekt/Models/Weather.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mittprojekt.Models
{
    public class Weather       //list of           
    {
        public double Temperature { get; set; }  //properties variables, just like  normal variables
        public double Humidity { get; set; }
        
        public double airpressure { get; set; }
        public double windspeed { get; set; }  
        public double rain { get; set; }

        public double snow { get; set; }

    }
}

mittprojekt/mittprojekt/Models/highesttemp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mittprojekt.Models
{
    public class highesttemp
    {
        public double AverageTemperature { get; set; }        //Average temperature
        public double HighestTemperature { get; set; }        //The highest temperature in skåne 
        public string CityWithHighestTemperature { get; set; }  //Where is the highest temperature
    }
} //en klass som ska göra någonting, public double

mittprojekt/mittprojekt/Controllers/WeatherController.cs
using mittprojekt.Helpers;
using mittprojekt.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace mittprojekt.Controllers
{
    public class WeatherController : Controller
    {
        //
        // GET: /Weather/
        public ActionResult Index(string city)
        {
            //loads temperature to given location the +city 

            string json = new WebClient().DownloadString("http://api.openweathermap.org/data/2.5/weather?q="+city); //downloads string from link, city = value from dropdown menu
            

            var serializer = new JavaScriptSerializer();
            serializer.RegisterConverters(new[] { new DynamicJsonConverter() });

            dynamic obj = serializer.Deserialize(json, typeof(object));


            double temperature = Convert.ToDouble(obj.main.temp) - 273.15;  //substracts to celsius 
            temperature = Math.Round(temperature, 2);                       //rounds numbers to digits 

            Weather myWeather = new Weather();                              
            myWeather.Temperature = temperature;                            //linked to above two rows of code
            myWeather.Humidity = Convert.ToDouble(obj.main.humidity);       
            myWeather.airpressure = Convert.ToDouble(obj.main.pressure);
            myWeather.windspeed = Convert.ToDouble(obj.wind.speed);
            //myWeather.rain = Convert.ToDouble(obj.rain.3h); 
            //myWeather.snow = Convert.ToDouble(obj.snow.3h); 


            return View(myWeather);                                         //returns results vellinge to view

           
        }
        
        
        
        
        public ActionResult AverageTemperature()
        {
            List<string> cities = new List<string>() { "Vellinge,se ", "Malmo,se", "Trelleborg,se", "Ystad,se", "Helsingborg,se", "Kristianstad.se", 
                "Landskrona,se", "Simrishamn,se", "Lund,se", "Ängelholm,se"};//list of cities to be averaged 

            var serializer = new JavaScriptSerializer();
            serializer.RegisterConverters(new[] { new DynamicJsonConverter() });


            double TotalTemperature = 0;  
            foreach(string city in cities)
            {
                string json = new WebClient().DownloadString("http://api.openweathermap.org/data/2.5/weather?q="+city); //downloads string from link 
                dynamic obj = serializer.Deserialize(json, typeof(object));
                TotalTemperature += Convert.ToDouble(obj.main.temp) - 273.15;
            }

            double averageTemp = TotalTemperature / 10; //divides total value with 3 
           

            return View(averageTemp);            
        }
        
	}
}

mittprojekt/mittprojekt/Controllers/homeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mittprojekt.Controllers
{
    public class homeController : Controller
    {
        //
        // GET: /home/  
        public ActionResult Index()             //random number controller 
        {
            Random r = new Random();
            int randomnumber = r.Next(0, 100);

            return View(randomnumber);
        }
        public ActionResult minsidatextpåallasidor() //links action to view 
        {
            Random r = new Random();
            int randomnumber = r.Next(0, 100);

            return View(randomnumber);                 
        }
        
        public ActionResult slump()  //
        {
            Random r = new Random();
            int randomnumber = r.Next(0, 100);

            return View(randomnumber);
        }
        
	}
}

mittprojekt/mittprojekt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html> <!--appears on all pages-->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    
    <div>Väderkollen</div>   <!--text appears on all pages name of the page-->
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>                                                                                                                                                                                                                                                                                                                                          

</body>
</html>

mittprojekt/mittprojekt/Views/Weather/AverageTemperature.cshtml
@model double
@{
    ViewBag.Title = "Genomsnittstempetarur"; <!-- Tab text-->
}

<h2>Genomsnittstemperatur</h2>
Snitt temperaturen är @Model C <!--returned value of averagetemperature -->

mittprojekt/mittprojekt/Views/Weather/Index.cshtml
@model mittprojekt.Models.Weather
@{
    ViewBag.Title = "Väderdata";
}

<h2>Index</h2>
@Html.ActionLink("Gå tillbaka och välj ny stad", "Index", "Home") <!--link back to the first page-->


<p>Temperaturen i vellinge är: @Model.Temperature</p>
<p>fuktighet @Model.Humidity %</p>
<p>lufttryck @Model.airpressure hpa</p>
<p>vindhastighet @Model.windspeed mps</p> 

 

mittprojekt/mittprojekt/Views/home/Index.cshtml
@model int
@{
    ViewBag.Title = "Väderkollen";   
}


<h2>Väderkollen</h2> <!--det här är en vy, den visar allting som händer under ytan-->

@Html.ActionLink("Klicka här för att se högsta temperatur i skåne", "AverageTemperature", "Weather")

@Html.ActionLink("Klicka här för att se snitttemperatur för skåne","AverageTemperature","Weather") <!--link for average temperature -->

<!--gör så att man kan se vilket stad som haft mest fint väder under en viss tid -->
<!--mest regn-->  <!---->

<form action="@Url.Action("Index", "Weather")">   <!--input button with dropdown for location-->
    <select name="city">
        <option value="Malmo,se">
            Malmö
        </option>
        <option value="Vellinge,se">
            Vellinge
        </option>
        <option value="Trelleborg,se">
            Trelleborg
        </option>
        <option value="Ystad.se">
            Ystad
        </option>
        <option value="Helsingborg,se">
            Helsingborg
        </option>
        <option value="Kristianstad,se">
            Kristianstad
        </option>
        <option value="Landskrona,se">
            Landskrona
        </option>
        <option value="Simrishamn,se">
            Simrishamn 
        </option>
        <option value="Lund,se">
            Lund
        </option>
        <option value="Ängelholm,se">
            Ängelholm
        </option>
    </select>
    <input type="submit" value="Visa värden för staden" /> 
</form>